# Generated by Django 3.2.6 on 2021-09-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypunk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
