# Generated by Django 3.2.6 on 2021-09-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypunk', '0002_alter_favourites_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='favourites',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
