# Generated by Django 3.2.6 on 2021-09-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypunk', '0003_auto_20210908_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
